### ISSUE TITLE
Update on the config.yaml of the pretrained unet

### ISSUE THREAD

**Issue by zwep** [NKI-AI/direct#249]
**Describe the bug**
When I solved the previous [issue](https://github.com/NKI-AI/direct/issues/248#issue-1705680536), and still in the same setting, other errors came up that relate to my [first issue](https://github.com/NKI-AI/direct/issues/243#issue-1703430209). 

These include errors such as 

```
omegaconf.errors.ConfigKeyError: Key 'scaling_key' not in 'TransformsConfig'
    full_key: inference.dataset.transforms.scaling_key
    reference_type=BaseConfig
    object_type=TransformsConfig

```

To resolve these I needed to adapt the provided config.yaml file that I downloaded from the model-zoo to the following:
```
...
inference:
  dataset:
    name: CalgaryCampinas
    lists: []
    regex_filter: null
    transforms:
      cropping:
        crop: null
        crop_type: uniform
        image_center_crop: true
      sensitivity_map_estimation:
        estimate_sensitivity_maps: true
        sensitivity_maps_gaussian: 0.7
      estimate_body_coil_image: false      
      pad_coils: null
      normalization:
        scaling_key: masked_kspace
      masking:
        name: ???
        accelerations:
        - 4
        center_fractions:
        - 0.08
        uniform_range: false
        image_center_crop: false
        val_accelerations:
        - 4
        - 8
        val_center_fractions:
        - 0.08
        - 0.04
    text_description: inference
    input_kspace_key: null
    input_image_key: null
    kspace_context: 0
    pass_mask: false
    crop_outer_slices: true
  batch_size: 8
...
```
Here I paste only the relevant part that contained the changes.

**Environment**
dlup version: Not installed. 
direct version: 1.0.5.dev0
How installed: using conda
Python version: 3.9
Operating System:
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
